#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Map from architecture reported by ansible to one used by apt and k8s
arc_map                :
  x86_64               :
    apt                : amd64
    k8s                : amd64
  armv7l               :
    apt                : armhf
    k8s                : arm
  aarch64              :
    apt                : arm64
    k8s                : arm64
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apt_repo_base          : http://apt.kubernetes.io 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Will use the first repo in this list that has release for then current architecture
# Applies to apt installations only
apt_repo_prefs         :
- kubernetes-disco
- kubernetes-cosmic
- kubernetes-bionic
- kubernetes-artful
- kubernetes-zesty
- kubernetes-xenial
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cni_urls               :
  weave                :
    manifests          :
    - "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  flannel              :
    cidr               : 10.244.0.0/16
    manifests          :
    - https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  cilium               :
    cidr               : 10.217.0.0/16
    helm               :
      repo             : https://helm.cilium.io
      chart            : cilium/cilium
      version          : 1.8.2
      overrides        :
        global.tunnel                 : vxlan
        global.autoDirectNodeRoutes   : false
        global.k8sServiceHost         : "{{ master.cplb_vip | default(ansible_default_ipv4.address, true) }}"
        global.k8sServicePort         : "{{ master.cplb_port | default(master.api_port, true) }}"
        global.hostFirewall           : true
        global.hostServices.enabled   : false
        global.hubble.enabled         : true
        global.hubble.listenAddress   : ":4244"
        global.hubble.metrics.enabled : "{dns,drop,tcp,flow,port-distribution,icmp,http}"
        global.hubble.relay.enabled   : true
        global.hubble.ui.enabled      : true
        global.hubble.metrics.port    : 9092

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
crypto_config          : /etc/kubernetes/pki/encryption.conf
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
