#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Install Docker
  shell             : curl -sSL get.docker.com | sh
  args              :
    warn            : False
    creates         : /usr/bin/docker
  notify            : Restart docker
  tags              :
  - docker
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Add user to docker group
  become            : True
  user              :
    name            : "{{ ansible_user_id }}"
    groups          :
    - docker
    append          : True
  tags              :
  - docker
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Copy daemon.json
  # For explanation, see: https://kubernetes.io/docs/setup/production-environment/container-runtimes
  become            : True
  copy              :
    src             : files/daemon.json
    dest            : /etc/docker/daemon.json
  notify            : Restart docker
  tags              :
  - docker
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
