#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Install Containerd
  when              :
  - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - ansible_distribution_major_version > 7
  become            : True
  action            :
    module          : "{{ ansible_pkg_mgr }}"
    name            : https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state           : present
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Install Docker
  shell             : curl -sSL get.docker.com | sh
  args              :
    warn            : False
    creates         : /usr/bin/docker
  register          : install_docker
  tags              :
  - docker
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Add user to docker group
  become            : True
  user              :
    name            : "{{ ansible_user_id }}"
    groups          :
    - docker
    append          : True
  tags              :
  - docker
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Copy daemon.json
  # For explanation, see: https://kubernetes.io/docs/setup/production-environment/container-runtimes
  become            : True
  copy              :
    src             : files/daemon.json
    dest            : /etc/docker/
  register          : daemon_json
  tags              :
  - docker
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- name              : Start docker
  become            : True
  systemd           :
    name            : docker.service
    state           : "{{ 'restarted' if install_docker.changed or daemon_json.changed else 'started' }}"
    enabled         : True
  no_log            : True # log for this is useless and verbose
  tags              :
  - docker
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
